# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "陈维龙 / Weilong Chen"
description              : "电子科技大学博士生，专注于智能电网与AI研究 / Ph.D. student at UESTC, focusing on Smart Grid and AI research"
repository               : "chenweilong915/chenweilong915.github.io"
google_scholar_stats_use_cdn : true

# Comments (Staticman)
staticman:
  branch: "main"

# reCaptcha (for spam protection)
reCaptcha:
  siteKey: "6LeIrSQUAAAAAKnBz0K9xZJr_dGnLHsz-PEE9Gq_"
  secret: "6LeIrSQUAAAAAKnBz0K9xZJr_dGnLHsz-PEE9Gq_"

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification : "googlec68b99088a216484"  # Google Search Console 验证码
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# 结构化数据 / Structured Data for SEO
structured_data:
  type: "Person"
  name: "陈维龙 / Weilong Chen"
  alternateName: 
    - "陈伟龙"
    - "维龙" 
    - "Weilong"
    - "Chen Weilong"
    - "Wei-long Chen"
  jobTitle: "博士研究生 / PhD Student"
  affiliation: "电子科技大学 / University of Electronic Science and Technology of China"
  address: "成都市，四川省，中国 / Chengdu, Sichuan, China"
  alumniOf: "电子科技大学 / University of Electronic Science and Technology of China"
  knowsAbout: 
    - "智能电网 / Smart Grid"
    - "人工智能 / Artificial Intelligence" 
    - "机器学习 / Machine Learning"
    - "联邦学习 / Federated Learning"
    - "深度学习 / Deep Learning"
    - "时间序列分析 / Time Series Analysis"
  sameAs:
    - "https://scholar.google.com/citations?user=ukaTvisAAAAJ"
    - "https://github.com/chenweilong915"
    - "https://chenweilong915.github.io"

# Site Author
author:
  name             : "陈维龙 / Weilong Chen"
  avatar           : "images/18598907.png"
  bio              : "电子科技大学 / University of Electronic Science and Technology of China"
  location         : "成都，中国 / Chengdu, China"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=ukaTvisAAAAJ"
  email            : "chenweilong921@gmail.com"
  researchgate     :  # e.g., "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : chenweilong915
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : # e.g., "linkedin username"
  dblp             : # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : # e.g., "https://orcid.org/xxxx"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# 中英文网站配置 / Bilingual Site Configuration
locale: "zh-CN"
date_format: "%Y年%m月%d日"

# 网站语言配置 / Site Language Configuration
languages:
  zh:
    name: "中文"
    title: "陈维龙的学术主页"
    description: "电子科技大学博士生，专注于智能电网与AI研究"
    navigation:
      about: "关于我"
      educations: "教育经历"
      research: "研究方向"
      news: "最新动态"
      honors: "荣誉奖项"
      work: "工作经历"
      talks: "受邀报告"
      publications: "学术论文"
      guestbook: "留言板"
      stats: "网站统计"
  en:
    name: "English"
    title: "Weilong Chen's Academic Homepage"
    description: "Ph.D. student at UESTC, focusing on Smart Grid and AI research"
    navigation:
      about: "About Me"
      educations: "Educations"
      research: "Research"
      news: "News"
      honors: "Honors and Awards"
      work: "Work Experience"
      talks: "Invited Talks"
      publications: "Publications"
      guestbook: "Guestbook"
      stats: "Site Statistics"

# 网站元信息 / Site Meta Information
meta:
  keywords: "陈维龙,陈伟龙,维龙,Weilong Chen,Weilong,Chen Weilong,Chen,电子科技大学,UESTC,University of Electronic Science and Technology of China,智能电网,Smart Grid,AI,人工智能,Artificial Intelligence,机器学习,Machine Learning,联邦学习,Federated Learning,博士生,PhD Student,PhD,博士,成都,Chengdu,四川,Sichuan,中国,China,研究生,Graduate Student,计算机科学,Computer Science,电气工程,Electrical Engineering,张彦如,Yanru Zhang,韩竹,Zhu Han,休斯顿大学,University of Houston,访问学者,Visiting Scholar,IEEE,ACM,论文,Paper,Research,研究,学术,Academic,Scholar,Google Scholar,GitHub,ResearchGate,DBLP,ORCID"
  author_keywords: "陈维龙,陈伟龙,维龙,Weilong Chen,Weilong,Chen Weilong,研究者,学者,博士生,博士,人工智能专家,智能电网专家,机器学习研究员,联邦学习,电子科技大学博士,UESTC PhD,Researcher,Scholar,PhD Student,PhD Candidate,Artificial Intelligence Researcher,Smart Grid Expert,Machine Learning Researcher,Federated Learning Specialist,Computer Scientist,Electrical Engineer"
  
# SEO优化关键词 / SEO Optimization Keywords  
seo:
  primary_keywords: 
    - "陈维龙"
    - "陈伟龙" 
    - "维龙"
    - "Weilong Chen"
    - "Weilong"
    - "Chen Weilong"
    - "Weilong Chen UESTC"
    - "陈维龙 电子科技大学"
    - "陈伟龙 UESTC"
  
  academic_keywords:
    - "Weilong Chen Smart Grid"
    - "Weilong Chen AI"
    - "Weilong Chen Machine Learning"
    - "Weilong Chen Federated Learning"
    - "陈维龙 智能电网"
    - "陈维龙 人工智能"
    - "陈维龙 机器学习"
    - "陈维龙 联邦学习"
    - "Weilong Chen UESTC PhD"
    - "Weilong Chen University of Electronic Science and Technology"
    - "Weilong Chen IEEE"
    - "Weilong Chen ACM"
    - "Weilong Chen Google Scholar"
    - "陈维龙 博士"
    - "陈维龙 研究生"
    
  research_keywords:
    - "Weilong Chen publications"
    - "Weilong Chen papers"
    - "Weilong Chen research"
    - "Weilong Chen TSG"
    - "Weilong Chen TKDE"
    - "Weilong Chen TMC"
    - "陈维龙 论文"
    - "陈维龙 研究"
    - "陈维龙 发表"
    - "Weilong Chen Yanru Zhang"
    - "Weilong Chen Zhu Han"
    - "Weilong Chen University of Houston"
    
  location_keywords:
    - "Weilong Chen Chengdu"
    - "Weilong Chen Sichuan"
    - "Weilong Chen China"
    - "陈维龙 成都"
    - "陈维龙 四川"
    - "陈维龙 中国"
    - "UESTC Weilong Chen"
    - "电子科技大学 陈维龙"
  
# 社交媒体配置 / Social Media Configuration  
social:
  google_scholar: "https://scholar.google.com/citations?user=ukaTvisAAAAJ"
  github: "https://github.com/chenweilong915"
  email: "chenweilong921@gmail.com"
  linkedin: "https://linkedin.com/in/weilong-chen"
  
# 统计配置 / Analytics Configuration
analytics:
  enable_visitor_stats: true
  enable_realtime_stats: true
  update_frequency: "daily"  # daily, weekly, monthly
  
# 评论系统配置 / Comments System Configuration
comments:
  provider: "formspree"  # staticman, formspree, disqus
  formspree:
    form_id: "mqadwkol"
    email_notifications: true
    
# 多语言内容配置 / Multilingual Content Configuration
content:
  show_bilingual: true
  default_language: "zh"
  gray_secondary_language: true  # 将次要语言显示为灰色
  
# 网站功能配置 / Site Features Configuration
features:
  google_scholar_integration: true
  github_stats: true
  visitor_counter: true
  real_time_stats: true
  contact_form: true
  academic_timeline: true
