# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "陈伟龙 / Weilong Chen"
description              : "电子科技大学博士生，专注于智能电网与AI研究 / Ph.D. student at UESTC, focusing on Smart Grid and AI research"
repository               : "chenweilong915/chenweilong915.github.io"
google_scholar_stats_use_cdn : true

# Comments (Staticman)
staticman:
  branch: "main"

# reCaptcha (for spam protection)
reCaptcha:
  siteKey: "6LeIrSQUAAAAAKnBz0K9xZJr_dGnLHsz-PEE9Gq_"
  secret: "6LeIrSQUAAAAAKnBz0K9xZJr_dGnLHsz-PEE9Gq_"

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "陈伟龙 / Weilong Chen"
  avatar           : "images/18598907.png"
  bio              : "电子科技大学 / University of Electronic Science and Technology of China"
  location         : "成都，中国 / Chengdu, China"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=ukaTvisAAAAJ"
  email            : "chenweilong921@gmail.com"
  researchgate     :  # e.g., "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : chenweilong915
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : # e.g., "linkedin username"
  dblp             : # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : # e.g., "https://orcid.org/xxxx"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# 中英文网站配置 / Bilingual Site Configuration
locale: "zh-CN"
date_format: "%Y年%m月%d日"

# 网站语言配置 / Site Language Configuration
languages:
  zh:
    name: "中文"
    title: "陈伟龙的学术主页"
    description: "电子科技大学博士生，专注于智能电网与AI研究"
    navigation:
      about: "关于我"
      educations: "教育经历"
      research: "研究方向"
      news: "最新动态"
      honors: "荣誉奖项"
      work: "工作经历"
      talks: "受邀报告"
      publications: "学术论文"
      guestbook: "留言板"
      stats: "网站统计"
  en:
    name: "English"
    title: "Weilong Chen's Academic Homepage"
    description: "Ph.D. student at UESTC, focusing on Smart Grid and AI research"
    navigation:
      about: "About Me"
      educations: "Educations"
      research: "Research"
      news: "News"
      honors: "Honors and Awards"
      work: "Work Experience"
      talks: "Invited Talks"
      publications: "Publications"
      guestbook: "Guestbook"
      stats: "Site Statistics"

# 网站元信息 / Site Meta Information
meta:
  keywords: "陈伟龙,Weilong Chen,电子科技大学,UESTC,智能电网,Smart Grid,AI,机器学习,Machine Learning,联邦学习,Federated Learning,博士生,PhD Student"
  author_keywords: "研究者,学者,博士生,人工智能,智能电网,Researcher,Scholar,PhD Student,Artificial Intelligence,Smart Grid"
  
# 社交媒体配置 / Social Media Configuration  
social:
  google_scholar: "https://scholar.google.com/citations?user=ukaTvisAAAAJ"
  github: "https://github.com/chenweilong915"
  email: "chenweilong921@gmail.com"
  linkedin: "https://linkedin.com/in/weilong-chen"
  
# 统计配置 / Analytics Configuration
analytics:
  enable_visitor_stats: true
  enable_realtime_stats: true
  update_frequency: "daily"  # daily, weekly, monthly
  
# 评论系统配置 / Comments System Configuration
comments:
  provider: "formspree"  # staticman, formspree, disqus
  formspree:
    form_id: "mqadwkol"
    email_notifications: true
    
# 多语言内容配置 / Multilingual Content Configuration
content:
  show_bilingual: true
  default_language: "zh"
  gray_secondary_language: true  # 将次要语言显示为灰色
  
# 网站功能配置 / Site Features Configuration
features:
  google_scholar_integration: true
  github_stats: true
  visitor_counter: true
  real_time_stats: true
  contact_form: true
  academic_timeline: true
